### ISSUE TITLE
Manajemen Karyawan

### ISSUE THREAD

**Issue by ncflsy** [adella-kitchen/adella-website#12]
- [x] Admin dapat menambahkan karyawan baru
- [x] Admin dapat mengedit data karyawan
- [x] Admin dapat menghapus karyawan
- [ ] Admin mendapatkan popup validasi sebelum menghapus data karyawan

**Comment by FachruddinFahma** [comment]
kurang validasi bang

**Comment by ncflsy** [comment]
wokee, validasi pas ngehapus kann? kalo udah langsung checklist bang
